[mail]
receivers = ["hello@163.com", "world@163.com"]
server_user = "test@163.com"
server_password = "123456"
server_host = "smtp.163.com"
server_port = 25


[slack]
url = "https://hooks.slack.com/services/xxxx/xxx/xxxx"
channel = "exception"
timeout = 6


[webhook]
url = "http://my.webhook.com"
timeout = 6


[bearychat]
url = "https://hook.bearychat.com/xxx/xxxx"
channel = "alert"
timeout = 6


[feishu]
url = "https://hook.feishu.com/xxx/xxxx?signKey=it_is_optional"
timeout = 6